config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  
  root 'products#index'
  get 'logout' => 'users#logout'

  resources :users, only: [:show, :new, :create, :index,]

  #商品ページ
  get  'sell',   to: 'products#new',    as: :new_product
  post 'sell',   to: 'products#create', as: :create_product
  resources :products, only: [:new,:create,:show,:edit,:update,:destroy] do
    member do
      get 'confirm'
      post 'pay' => 'products#pay'
    end
  end




end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :category
  belongs_to_active_hash :state
  belongs_to_active_hash :delivery_cost
  belongs_to_active_hash :delivery_method
  belongs_to_active_hash :delivery_date
  belongs_to :category

  has_many :images, dependent: :destroy
  belongs_to :user



  validates :name,:introduction,:price,:category,:state,:delivery_cost,:prefecture,:delivery_method,:delivery_date,:user_id, presence: true
  validates :name,length:{ maximum: 40 }
  validates :introduction,length:{ maximum: 1000 }
  validates :price, numericality:{ greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}

  enum status: {
    not_sale: 0, sale:1, soldout:2
  }, _prefix: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  require "payjp"
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_product, only: [:edit, :update, :show, :destroy, :confirm, :pay]

  def index
    @products = Product.includes(:images)
  end

  def new
    @product = Product.new
    @image = Image.new
  end
  
  def create
    @product = Product.new(product_params)
    if @product.save & save_images(@product,image_params)
      redirect_to root_path
      flash[:notice] = "出品しました"
    else
      @image = Image.new
      flash[:notice] = "画像がない、もしくは未入力の欄があります"
      render action: :new
      @product.destroy
    end
  end

  def show
    @products = Product.includes(:images)
  end

  def edit
    @image = Image.new
  end

  def update
    if @product.update(product_params) 
      remove_product_images
    else
      render :edit
    end
  end

  def destroy
    @product.destroy if @product.user.id === current_user.id
    redirect_to root_path
  end

  def confirm
    @products = Product.includes(:images)
  end

  def pay
    Payjp.api_key = "sk_test_601fb5e6f2e07120aaf7ef8a"
    Payjp::Charge.create(
      amount: @product.price, # 決済する値段
      card: params['payjp-token'], # フォームを送信すると作成・送信されてくるトークン
      currency: 'jpy'
    )
      @product.update(buyer_id: current_user.id, status: 2)
      redirect_to root_path, notice: '商品を購入しました'
  end


  private

  def product_params
    params.require(:product).permit(
      :name,
      :introduction,
      :price,
      :size,
      :state_id,
      :brand,
      :category_id,
      :delivery_date_id,
      :delivery_cost_id,
      :delivery_method_id,
      :prefecture_id,
      :buyer_id
    ).merge(user_id: current_user.id)
  end

  def image_params
    params.require(:images).require(:name).permit(params[:images][:name].keys) if params[:images].present?
  end

  def save_images(product, images)
    if images.present?
      return false if product.id.blank?
      images.values.each do |name|
        @image = product.images.create(name: name)
      end
    else
      return false
    end
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def remove_product_images
    @product.images.each do |image|
      image.destroy
    end
    if save_images(@product, image_params)
      redirect_to root_path
      flash[:notice] = "商品情報を編集しました"      
    else
      @image = Image.new
      flash[:notice] = "画像がない、もしくは未入力の欄があります"
      render :edit
    end
  end

end

app/views/products/_box-contents.html.haml
.box-contents
  - @products.order('created_at DESC').limit(5).each do |product|
    .items-box
      .items-box_photo
        = link_to product_path(id: product.id) do
          = product.images.present? ? (image_tag product.images.first.name.url, alt: '商品画像') : (image_tag 'common/no_image.png', alt: '画像がありません')
          -if product.status == "soldout"
            .soldout
      .items-box_body
        %h3.items-box-name
          = product.name
        .items-box-num
          .items-box-price
            ¥ 
            = product.price
          .items-box-icon
            %i.far.fa-heart
        .items-box-tax
          (税込)
.view-all
  %a{ href:'', class:"text-center__inner"}
    すべての商品を見る   

app/views/products/_product_form.html.haml
.product-exhibition__header 
  .product-exhibition__header__logo
    = image_tag "common/logo.svg", alt: "mercari", height: "49", width: "185"

.body
  .product-exhibition
    .product-exhibition__head 商品情報を入力
    = form_for(@product, url: url, method: method.to_sym, html: { class: 'product-exhibition__form' } ) do |f|
      
      -# 出品画像
      .product-exhibition__form__group
        .product-exhibition__form__group__item
          %span.product-exhibition__form__group__item__large-label 出品画像
          %span.product-exhibition__form__group__item__necessary 必須
        %p.product-exhibition__form__group__notice 
        .product-exhibition__form__group__image
          =f.fields_for @image do |fi|
            %ul.image-preview
            .nest-form
              .nest-form__head
                %p クリックしてファイルをアップロード
              = fi.file_field :name, name: 'images[name][1]',id: 'image1', style: 'display: none;'


      -# 商品名、商品の説明
      .product-exhibition__form__group
        .product-exhibition__form__group__intro
          .product-exhibition__form__group__item
            %span.product-exhibition__form__group__item__label 商品名
            %span.product-exhibition__form__group__item__necessary 必須
          .product-exhibition__form__group__text-box
            = f.text_field :name, autofocus: true, class: "product-exhibition__form__group__text-box__field__name", placeholder: "商品名（必須40文字まで）"
          .product-exhibition__form__group__item
            %span.product-exhibition__form__group__item__label 商品の説明
            %span.product-exhibition__form__group__item__necessary 必須
          .product-exhibition__form__group__text-box
            = f.text_area :introduction, autofocus: true, class: "product-exhibition__form__group__text-box__area", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
      

      -# 商品の詳細
      .product-exhibition__form__group
        .product-exhibition__form__group__detail
          %span.product-exhibition__form__group__small-label 商品の詳細
          .product-exhibition__form__group__detail-list
            .product-exhibition__form__group__select-box__category
              .product-exhibition__form__group__item
                %span.product-exhibition__form__group__item__label カテゴリー
                %span.product-exhibition__form__group__item__necessary 必須
              .product-exhibition__form__group__select-box
                = f.collection_select :category_id, Category.all, :id, :name, {include_blank: "---"}, class: "product-exhibition__form__group__select-box__body"
            .product-exhibition__form__group__select-box__state
              .product-exhibition__form__group__item
                %span.product-exhibition__form__group__item__label 商品の状態
                %span.product-exhibition__form__group__item__necessary 必須
              .product-exhibition__form__group__select-box
                = f.collection_select :state_id, State.all, :id, :name, {include_blank: "---"}, class: "product-exhibition__form__group__select-box__body"


      -# 配送に付いて
      .product-exhibition__form__group
        .product-exhibition__form__group__delivery
          %span.product-exhibition__form__group__small-label 配送について
          %span.product-exhibition__form__group__help
            = link_to "?"

          .product-exhibition__form__group__delivery__list
            .product-exhibition__form__group__item            
              %span.product-exhibition__form__group__item__label 配送料の負担
              %span.product-exhibition__form__group__item__necessary 必須
            .product-exhibition__form__group__select-box__delivery_cost
              = f.collection_select :delivery_cost_id, DeliveryCost.all, :id, :name, {include_blank: "---"}, class: "product-exhibition__form__group__select-box__body" 
            
            .product-exhibition__form__group__item
              %span.product-exhibition__form__group__item__label 配送の方法
              %span.product-exhibition__form__group__item__necessary 必須
            .product-exhibition__form__group__select-box__delivery_method
              = f.collection_select :delivery_method_id, DeliveryMethod.all, :id, :name, {include_blank: "---"}, class: "product-exhibition__form__group__select-box__body" 

            .product-exhibition__form__group__item
              %span.product-exhibition__form__group__item__label 発送元の地域
              %span.product-exhibition__form__group__item__necessary 必須
            .product-exhibition__form__group__select-box__delivery_prefecture
              = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: "---"}, class: "product-exhibition__form__group__select-box__body" 

            .product-exhibition__form__group__item
              %span.product-exhibition__form__group__item__label 発送までの日数
              %span.product-exhibition__form__group__item__necessary 必須
            .product-exhibition__form__group__select-box__delivery_date
              = f.collection_select :delivery_date_id, DeliveryDate.all, :id, :name, {include_blank: "---"}, class: "product-exhibition__form__group__select-box__body"


      -# 販売価格
      .product-exhibition__form__group
        .product-exhibition__form__group__sell-price
          %span.product-exhibition__form__group__small-label 販売価格(300〜9,999,999)
          %span.product-exhibition__form__group__help
            = link_to "?"
          
          .product-exhibition__form__group__sell-price__list
            .product-exhibition__form__group__sell-price__list__price
              .product-exhibition__form__group__sell-price__list__price__left
                %span.product-exhibition__form__group__item__label 価格
                %span.product-exhibition__form__group__item__necessary 必須
              .product-exhibition__form__group__sell-price__list__price__right
                %span ¥
                .product-exhibition__form__group__text-box
                  = f.text_field :price, autofocus: true, id: "product-exhibition__form__group__text-box__field__price",placeholder: "例）300",class: "product-exhibition__form__group__text-box__field__price"
            
            .product-exhibition__form__group__sell-price__list__fee
              .product-exhibition__form__group__sell-price__list__fee__left
                %p 販売手数料(10%)
              .product-exhibition__form__group__sell-price__list__fee__right
                %p.sell-fee -
            
            .product-exhibition__form__group__sell-price__list__profit
              .product-exhibition__form__group__sell-price__list__profit__left
                %p 販売利益
              .product-exhibition__form__group__sell-price__list__profit__right
                %p.sell-profit -


      -# 確認事項、出品ボタン、もどるボタン
      .product-exhibition__form__group
        %p
          = link_to "禁止されている出品"
          %span 、
          = link_to "行為"
          %span を必ずご確認ください。
        %p 
          %span またブランド品でシリアルナンバー等がある場合はご記載ください。
          %span 
          =link_to "偽ブランドの販売"
          %span は犯罪であり処罰される可能性があります。
        %p 
          %span また、出品をもちまして
          %span 
          =link_to "加盟店規約"
          %span に同意したことになります。
        .product-exhibition__form__group__actions
          = f.submit "出品する"
        .product-exhibition__form__group__return
          = link_to "もどる" ,root_path, class: "product-exhibition__form__group__return"


.product-exhibition__footer 
  %span.product-exhibition__footer__policy 
    = link_to "プライバシーポリシー"
  %span.product-exhibition__footer__terms 
    = link_to "メルカリ利用規約"
  %span.product-exhibition__footer__law
    = link_to "特定商取引に関する表記"
  .product-exhibition__footer__logo
    = image_tag 'common/logo-gray.svg', alt: 'mercari', height: '65', width: '80'
  .product-exhibition__footer__trademark ©️ 2019 Mercari

app/views/products/confirm.html.haml
.sub-wrapper.confirm-page
  = render partial: "layouts/sub-header" 
  %main.sub-container
    .panel
      %section.panel__head 購入内容の確認
      .panel__inner
        %section.buy-content
          .item-info
            %h3.item-info__image
              = @product.images.present? ? (image_tag @product.images.first.name.url, alt: '商品画像', class: "confirm-image") : (image_tag 'common/no_image.png', alt: '画像がありません')
            %p.item-info__name
              = @product.name
            %ul.buy-price
              %li.buy-price__inner
                .buy-price__inner__cell 支払い金額
                .buy-price__inner__cell 
                  = "¥ #{number_with_delimiter@product.price}"
              %p
                -#=link_to "購入する", pay_path(current_user.id), class: "buy-confirm-btn"
                = form_with url: pay_product_path do
                  :plain
                    <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key="pk_test_415c1e8b20431b96ce1eb587"></script>
        %hr.line
        %section.buy-content
          .user-info
            %h3.user-info__header 配送先
            %adress.user-info__text
              %p
                = "〒#{current_user.postal_code.to_s.insert(3, '-')}"
                %br
                = "#{current_user.prefecture} #{current_user.city}"
                %br
                = current_user.address
                %br
                = current_user.building
                %br
                =current_user.name
              %p.link-to-change.icon-arrow-r
                =link_to "変更する"

= render partial: "layouts/sub-footer"

app/views/products/edit.html.haml
= render partial: 'product_form', locals: { url: product_path, method: 'patch' }

app/views/products/index.html.haml
= render partial: "layouts/header" 

.container
  .slideshow
    %div.slick
      %div
        = image_tag "https://www-mercari-jp.akamaized.net/assets/img/featured/camp/index/index_keyvisual.png?2482339763"
      %div
        = image_tag "https://mercarinews.files.wordpress.com/2019/08/sns-1.jpg"

  .container__main
    %h2 ピックアップカテゴリー
    .pickup-box  
      = link_to "レディース新着アイテム"
    =render partial: 'products/pickup/ladies'

    .pickup-box  
      = link_to "メンズ新着アイテム"
    =render partial: 'products/pickup/mens'

    .pickup-box  
      = link_to "ベビー・キッズ 新着アイテム"
    =render partial: 'products/pickup/kids'

  .aside
    .aside__banner


.sell-button
  = link_to new_product_path do
    %h3.sell-button__text 出品
    .i.fa.fa-camera.fa-4x

.banner
  .banner__pc
    .banner__pc__inner
      %h2スマホでかんたんフリマアプリ
      %p今すぐ無料ダウンロード!
    .banner__pc__app
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?2927923569", class: "mercari"
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?2927923569", class: "app"
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?2927923569", class: "google"
    .banner__pc__img
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?891577966", class: "img"


= render partial: "layouts/footer" 

app/views/products/new.html.haml
= render partial: 'product_form', locals: { url: create_product_path, method: 'post' }

app/views/products/pay.html.haml
= form_tag action: :pay, method: :post do
  :plain
    <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key="pk_test_415c1e8b20431b96ce1eb587"></script>

app/views/products/show.html.haml
.container
  = render "layouts/header"
  %section.item-box-container
    %h1.item-name  
      = @product.name
    .item-main-content
      .item-photo
        = @product.images.present? ? (image_tag @product.images.first.name.url, alt: '商品画像') : (image_tag 'common/no_image.png', alt: '画像がありません')
        -if @product.status == "soldout"
          .soldout
      %table.item-detail-table
        %tbody
          %tr
            %th 出品者
            %td
              = link_to "#{@product.user.name}",'#'
              .item-user-ratings
                %i.fa.fa-smile-o 
                %span 42
                %i.fa.fa-meh-o
                %span 10
                %i.fa.fa-frown-o
                %span 0
          %tr
            %th カテゴリー
            %td
              = link_to "#{@product.category.name}", "#"

          %tr
            %th ブランド
            %td 
              
          %tr
            %th 商品の状態
            %td= @product.state.name
          %tr
            %th 配送料の負担
            %td= @product.delivery_cost.name
              
          %tr
            %th 配送の方法
            %td= @product.delivery_method.name

          %tr
            %th 配送元地域
            %td= link_to "#{@product.prefecture.name}", "#"
          %tr
            %th 発送日の目安
            %td= @product.delivery_date.name
          
      .item-price-box
        %span.item-price  
          = "¥ #{number_with_delimiter@product.price}"
        %span.item-tax (税込)
        %span.item-shipping-fee 送料込み

        - if @product.status == "soldout"
          .sold-out-btn 売り切れました
        - elsif user_signed_in? && current_user.id != @product.user.id
          .buy-btn
            = link_to "購入画面に進む", confirm_product_path(params[:id])

      .item-description
        %p.item-description-inner
          = @product.introduction
        

      .item-button-container.clearfix
        .item-button-left
          %button.item-button.item-button-like
            %i.fa.fa-heart
            %span いいね!
            %span.fade-in-down 11
          %a.item-button.item-button-report.clearfix
            %i.fa.fa-flag
            %span 不適切な商品の報告
        .item-button-right
          = link_to "#" do
            %i.fa.fa-lock
            %span あんしん・あんぜんへの取り組み

  - if user_signed_in?  && current_user.id == @product.user.id
    .item-detail-for_seller
      = link_to "商品の編集", edit_product_path(@product),class: "edit-btn"
      %p or
      = link_to "この商品を削除する", product_path(@product), method: :delete,data: { confirm: "本当に削除しますか？" }, class: "delete-btn"

  .item-detail-message
    .message-container
      .message-content
        .message-form{action: "#", method: "POST"}
          %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %textarea
          %button
            %span コメントする



.banner
  .banner__pc
    .banner__pc__inner
      %h2スマホでかんたんフリマアプリ
      %p今すぐ無料ダウンロード!
    .banner__pc__app
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?2927923569", class: "mercari"
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?2927923569", class: "app"
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?2927923569", class: "google"
    .banner__pc__img
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?891577966", class: "img"

= render "layouts/footer" 