config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  
  root 'products#index'
  get 'logout' => 'users#logout'

  resources :users, only: [:show, :new, :create, :index,]

  #商品ページ
  get  'sell',   to: 'products#new',    as: :new_product
  post 'sell',   to: 'products#create', as: :create_product
  resources :products, only: [:new,:create,:show,:edit,:update,:destroy] do
    member do
      get 'confirm'
      post 'pay' => 'products#pay'
    end
  end




end

app/views/layouts/_footer.html.haml
.footer
  %ul.footer__navigation
    %li.footer__navigation__item
      %h2 メルカリについて
      %ul
        %li
          = link_to "会社概要（運営会社）"
        %li
          = link_to "採用情報"
        %li
          = link_to "プレスリリース"
        %li
          = link_to "公式ブログ"
        %li
          = link_to "メルカリロゴ利用ガイドライン"
        %li
          = link_to "TWITTER"
        %li
          = link_to "FACEBOOK"

    %li.footer__navigation__item
      %h2 ヘルプ＆ガイド
      %ul
        %li
          = link_to "メルカリガイド"
        %li
          = link_to "らくらくメルカリ便"
        %li
          = link_to "ゆうゆうメルカリ便"
        %li
          = link_to "大型メルカリ便"  
        %li
          = link_to "車体取引ガイド"
        %li
          = link_to "メルカリあんしん・あんぜん宣言！" 
        %li
          = link_to "偽ブランド品撲滅への取り組み" 
        %li
          = link_to "メルカリボックス" 

    %li.footer__navigation__item
      %h2 プライバシーと利用規約
      %ul.footer__navigation__one
        %li
          = link_to "プライバシーポリシー"
        %li
          = link_to "メルカリ利用規約"
        %li
          = link_to "あんしんスマホサポート制度に関する利用特約"
        %li
          = link_to "コンプライアンスポリシー" 
      %ul.footer__navigation__two
        %li
          = link_to "個人データの安全管理に関わる基本方針"
        %li
          = link_to "特定商取引に関する表記" 
        %li
          = link_to "資金決算法基づく表示"
        %li
          = link_to "法令遵守に基づく表示"
    %li.footer__navigation__item
      %h2 国
      %ul
        %li
          = link_to "日本"
        %li
          = link_to "United States"
  .footer__logo
    .footer__logo-mercari
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?803630998", class: "logo__search"
    .footer__logo-copyright
      %P © 2019 Mercari

app/views/layouts/_header.html.haml
.header
  .header__container
    .header__container__search
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2927923569", class: "header__container__search__logo"
      = form_with local: true, class: "header__container__search__form" do |f|
        = f.text_field :keyword, class: "header__container__search__input", type: "search", name: "keyword", placeholder: "何かお探しですか？"        
    .header__container__navigation
      .navigation-left
      -#
        %ul#dropmenu
          %li
            .i.fa.fa-bars
            = link_to 'カテゴリから探す', '#'
            %ul
              %li
                = link_to 'レディース', '#'
              %li
                = link_to 'メンズ', '#'
              %li
                = link_to 'メンズ', '#'
        %ul#dropmenu
          %li
            .i.fa.fa-tags
            = link_to 'ブランドから探す', '#'
            %ul
              %li
                = link_to 'シャネル', '#'
              %li
                = link_to 'ナイキ', '#'
      .navigation-right
        %ul.header-user-nav
          - if user_signed_in?
            %li
              = link_to('#', class: 'link') do
                %i.icon.fa.fa-heart-o
                %span いいね!一覧
            %li
              = link_to('#', class: 'link') do
                %i.icon.fa.fa-bell-o
                  .nav-count 5
                %span お知らせ
              %ul
                %li
                  = link_to user_path(current_user.id),class: "sublink" do
                    .sublink-content-logo
                      =image_tag "common/logo-gray.svg", size: "40x40", alt: "mercari"
                    .sublink-content-text
                      %span 3日後、P999還元お得チケットの有効期限が切れます！タップして詳細を確認しましょう。
                      %i.fa.fa-chevron-right
                %li
                  = link_to user_path(current_user.id),class: "sublink" do
                    .sublink-content-logo
                      =image_tag "common/logo-gray.svg", size: "40x40", alt: "mercari"
                    .sublink-content-text
                      %span 【あと2日】参加ボタンを押すだけでポイントがもらえる！総額1億円相当還元！詳しくはこちら
                      %i.fa.fa-chevron-right
                %li
                  = link_to user_path(current_user.id),class: "sublink" do
                    .sublink-content-logo
                      =image_tag "common/logo-gray.svg", size: "40x40", alt: "mercari"
                    .sublink-content-text
                      %span 事務局から個別メッセージ「ログイン通知」
                      %i.fa.fa-chevron-right
                %li
                  = link_to user_path(current_user.id),class: "sublink" do
                    .sublink-content-logo
                      =image_tag "common/logo-gray.svg", size: "40x40", alt: "mercari"
                    .sublink-content-text
                      %span 《ご登録記念》¥1,000の商品を「実質1円」でご購入いただけます！
                      %i.fa.fa-chevron-right
                %li
                  = link_to user_path(current_user.id),class: "sublink" do
                    .sublink-content-logo
                      =image_tag "common/logo-gray.svg", size: "40x40", alt: "mercari"
                    .sublink-content-text
                      %span 【スマホを売ろう！】メルカリなら下取りよりも高く売れる♪いますぐ相場チェック！
                      %i.fa.fa-chevron-right
            %li
              = link_to('#', class: 'link') do
                %i.icon.fa.fa-check
                %span やることリスト
              %ul
                %li
                  = link_to (''),class: "sublink-todo" do
                    .sublink-content-todo
                      .sublink-content-todo-logo
                        = image_tag "common/logo-gray.svg" ,size: "80x80"
                      .sublink-content-todo-text
                        %span 現在、やることリストはありません
            %li.list-mypage
              = link_to users_path(current_user.id) do
                %span マイページ
              %ul
                .sublink-mypage
                  %li
                    = image_tag "common/member_photo_noimage_thumb.png" ,size: "75x75", alt: "", class: "sublink-maypagemember_photo"
                  %li
                    = link_to users_path(current_user.id),class: "sublink-maypage-link" do
                      ユーザー名：#{current_user.name}
          - else
            .new-registration-btn
              = link_to '新規会員登録', new_user_path
            .log-in-btn
              = link_to 'ログイン', new_user_session_path

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_sub-footer.html.haml
%footer.sub-footer
  %ul.sub-footer__menu
    %li.sub-footer__menu__privacy
      = link_to "プライバシーポリシー", src: "#"
    %li.sub-footer__menu__terms
      = link_to "メルカリ利用規約", src: "#"
    %li.sub-footer__menu__notation
      = link_to "特定商取引に関する表記", src: "#"
  .sub-footer__logo
    = link_to root_path do
      = image_tag 'common/logo-gray.svg', height:'65px'
  .sub-footer__small-text
    %small © 2019 Mercari

app/views/layouts/_sub-header.html.haml
%header.sub-header
  = link_to root_path, class:"sub-header__logo" do
    = image_tag 'common/logo.svg', height:'49px'

app/views/layouts/application.html.haml
!!!
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
  %body
    .notifications
      - flash.each do |key, value|
        = content_tag(:div, value, class: key)
    = yield